controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    so101_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

so101_joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan
      - shoulder_lift
      - elbow_flex
      - wrist_flex
      - wrist_roll
      - gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: false
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 0.6
