[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
board_microros_transport = wifi
board_microros_distro = humble
monitor_speed = 115200
upload_speed = 921600
